
(defpackage #:cl-opencl-bindings
  (:use :cffi)
  (:nicknames :%cl)
  (:export #:unload-compiler
           #:char-16
           #:create-sampler
           #:enqueue-native-kernel
           #:get-kernel-info
           #:float
           #:get-event-info
           #:ushort
           #:get-platform-info
           #:enqueue-wait-for-events
           #:device-local-mem-type
           #:ushort-8
           #:float-8
           #:ushort-4
           #:ushort-2
           #:float-4
           #:float-2
           #:double-8
           #:double-4
           #:double-2
           #:release-program
           #:double
           #:platform-info
           #:ulong-8
           #:ulong-4
           #:ulong-2
           #:device-exec-capabilities
           #:kernel-info
           #:device-fp-config
           #:uchar
           #:short-4
           #:short-2
           #:get-event-profiling-info
           #:char-8
           #:char-4
           #:char-2
           #:wait-for-events
           #:create-image-3d
           #:create-image-2d
           #:retain-command-queue
           #:get-extension-function-address
           #:enqueue-copy-image
           #:double-16
           #:retain-program
           #:create-program-with-binary
           #:addressing-mode
           #:get-supported-image-formats
           #:get-platform-ids
           #:create-kernel
           #:release-mem-object
           #:release-kernel
           #:ushort-16
           #:device-address-info
           #:get-sampler-info
           #:sampler-info
           #:event-info
           #:enqueue-nd-range-kernel
           #:retain-event
           #:int-8
           #:get-kernel-work-group-info
           #:kernel-work-group-info
           #:uchar-8
           #:uchar-4
           #:uchar-2
           #:retain-kernel
           #:get-command-queue-info
           #:char
           #:int-8-t
           #:int-16
           #:command-type
           #:uint-8
           #:uint-4
           #:uint-2
           #:enqueue-unmap-mem-object
           #:get-context-info
           #:filter-mode
           #:get-mem-object-info
           #:enqueue-copy-buffer-to-image
           #:context-info
           #:short
           #:enqueue-read-image
           #:half
           #:uint16-t
           #:long
           #:release-event
           #:release-command-queue
           #:retain-context
           #:get-device-info
           #:device-info
           #:int-4
           #:int-2
           #:float-16
           #:mem-object-type
           #:profiling-info
           #:retain-sampler
           #:enqueue-map-image
           #:build-program
           #:enqueue-copy-image-to-buffer
           #:finish
           #:long-16
           #:mem-info
           #:enqueue-write-buffer
           #:short-16
           #:enqueue-write-image
           #:command-queue-info
           #:create-program-with-source
           #:enqueue-copy-buffer
           #:enqueue-task
           #:long-8
           #:long-4
           #:long-2
           #:int64-t
           #:release-context
           #:uint-16
           #:build-status
           #:get-program-info
           #:program-info
           #:create-buffer
           #:mem-flags
           #:create-command-queue
           #:flush
           #:get-device-ids
           #:platform-id
           #:enqueue-read-buffer
           #:release-sampler
           #:sampler
           #:short-8
           #:int16-t
           #:enqueue-barrier
           #:enqueue-marker
           #:set-kernel-arg
           #:set-command-queue-property
           #:command-queue-properties
           #:uchar-16
           #:uint8-t
           #:enqueue-map-buffer
           #:event
           #:map-flags
           #:bool
           #:command-queue
           #:ulong-16
           #:retain-mem-object
           #:create-context-from-type
           #:get-program-build-info
           #:program-build-info
           #:get-image-info
           #:size-t
           #:image-info
           #:mem
           #:create-context
           #:device-id
           #:context-properties
           #:intptr-t
           #:context
           #:create-kernels-in-program
           #:kernel
           #:program
           #:int
           #:int32-t
           #:image-format
           #:image-channel-data-type
           #:image-channel-order
           #:channel-type
           #:channel-order
           #:device-type
           #:bitfield
           #:ulong
           #:uint64-t
           #:device-mem-cache-type
           #:uint
           #:uint32-t
           #:error-code
           #:buffer-region
           #:size
           #:origin

           #:double-3
           #:float-3
           #:ulong-3
           #:short-3
           #:ushort-3
           #:char-3
           #:uchar-3
           #:int-3
           #:uint-3

           #:gl-int
           #:gl-uint
           #:gl-enum

           #:set-user-event-status
           #:enqueue-copy-buffer-rect
           #:set-mem-object-destructor-callback
           #:create-sub-buffer
           #:buffer-create-type
           #:enqueue-read-buffer-rect
           #:set-event-callback
           #:enqueue-write-buffer-rect
           #:create-user-event

           #:create-from-gl-buffer
           #:create-from-gl-texture-2d
           #:create-from-gl-texture-3d
           #:get-gl-context-info-khr
           #:create-from-gl-renderbuffer
           #:get-gl-object-info
           #:get-gl-texture-info
           #:enqueue-acquire-gl-objects
           #:enqueue-release-gl-objects
           #:command-execution-status))

